#!/bin/sh
# OpenWifiMap updater script
# By CyrusFox, basic hacked version ;)

fail() {
    echo "$1" 1>&2
    exit 1
}

get_rev() {
	echo -e "HEAD /openwifimap/$nodeid HTTP/1.1\r
User-Agent: ffmapupdate\r
Host: $map_server\r
Connection: close\r
\r
" | netcat -w 1 $map_server 80 > /tmp/owm_revision
	echo $(cat /tmp/owm_revision) | grep ETag | cut -d '"' -f2
}

send_update() {
	local rev=$(get_rev)
	if [ -z $rev ]; then 
		echo -e "PUT /openwifimap/$nodeid HTTP/1.1\r
User-Agent: ffmapupdate\r
Host: $map_server\r
Connection: close\r
Accept: */*\r
Content-Type: application/json\r
Content-Length: $(wc -c /tmp/map/$host.json | cut -d ' ' -f1 )\r
\r
$(cat /tmp/map/$host.json)\r
\r
" | netcat -v -w 1 $map_server 80 > /tmp/owm_update
	else
		echo -e "PUT /openwifimap/$nodeid?rev=$rev HTTP/1.1\r
User-Agent: ffmapupdate\r
Host: $map_server\r
Connection: close\r
Accept: */*\r
Content-Type: application/json\r
Content-Length: $(wc -c /tmp/map/$host.json | cut -d ' ' -f1 )\r
\r
$(cat /tmp/map/$host.json)\r
\r
" | netcat -v -w 1 $map_server 80 > /tmp/owm_update
	fi
}
update_map() {
	local host=$(cat /proc/sys/kernel/hostname) 
	if [ $(uci -q get owm.settings.public) == "true" -a $host != "ffnode" ]; then
	mkdir -p /tmp/map
	echo "Update node $host.$zonename on server $map_server"
	echo '{"type": "node", "hostname": "'$host.$zonename'", "longitude": '$lon', "latitude": '$lat', "lastupdate": "'$(date -u "+%Y-%m-%dT%H:%M:%SZ")'", "updateInterval": '$interval'}' > /tmp/map/"$host".json
	send_update
	else
		echo "Node is private or hostname is not set, not updating..."
	fi
}



printArgs () {
    fail "Usage:
$0 update_map
"
}
[ $# -lt 1 ] && printArgs

interval=$(uci -q get owm.settings.interval)
zonename=$(uci -q get owm.settings.zonename)
lat=$(uci -q get owm.settings.lat)
lon=$(uci -q get owm.settings.lon)
map_server=$(uci -q get owm.settings.map_server)
nodeid=$(cat /etc/nodeid)

[ -z $interval ] && fail "Interval not set in OWM config"
[ -z $zonename ] && fail "Zonename not set in OWM config"
[ -z $lat -o -z $lon ] && fail "Latitude or Longitude not set in OWM config"
[ -z $map_server ] && fail "Map server not set in OWM config"
[ -z $nodeid ] && fail "NodeID not set yet, please wait for NodeID script to run.."

case "$1" in
  --help|-h)
    printArgs
    ;;
  *)
    update_map
    ;;
esac
